spring.datasource.url=jdbc:postgresql://localhost:5432/orchestrator
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#ssh.host=192.168.1.10
#ssh.username=mihai
#ssh.key-path=/Users/alexs/.ssh/id_rsa
#storage.base-path=/opt/lab-data

ssh.host=193.226.6.116
ssh.username=infratest
ssh.key-path=/Users/alexs/.ssh/id_rsa
storage.base-path=/opt/lab-data
storage.container-path=/home/student