server.port=8081
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/orchestrator}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DB_USERNAME:postgres}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:}}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#ssh.host=192.168.1.10
#ssh.username=mihai
#ssh.key-path=/Users/alexs/.ssh/id_rsa
#storage.base-path=/opt/lab-data

ssh.host=${SSH_HOST:193.226.6.116}
ssh.username=${SSH_USERNAME:infratest}
ssh.key-path=${SSH_KEY_PATH:/Users/alexs/.ssh/id_rsa}
storage.base-path=${STORAGE_BASE_PATH:/home/infratest/lab-data}
storage.container-path=${STORAGE_CONTAINER_PATH:/home/student}

security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
security.jwt.expiration=86400000